name: mvc-movie
services:
  mvc-movie:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mvc-movie
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=@p4ssw0rd
      - MSSQL_PID=developer
    ports:
      - "1433:1433"
